version: "3.9"
services:
  scrabble-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scrabble_tiles:/app/scrabble_tiles:ro
    environment:
      - PYTHONUNBUFFERED=1